apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  namespace: opentraum
  labels:
    app: reservation-service
    app.kubernetes.io/part-of: opentraum
spec:
  selector:
    app: reservation-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
